### PR TITLE
Fix size calculation for MariaDB

### PR DESCRIPTION
**Pull request by MorrisJobke**
The checks where there for a MySQL 3.23, 3.4 and 3.5 🙈

With this change now also my production server properly shows the size of my MariaDB instance ;)

I will create a backport and also fix the survey_client

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Best viewed without whitespace diff https://github.com/nextcloud/serverinfo/pull/34/files?w=1

cc @rullzer @LukasReschke @nickvergessen @schiessle

**Comment by schiessle** [comment]
:+1:

**Comment by schiessle** [comment]
@MorrisJobke can you have a look at the merge conflicts? Thanks!

**Comment by MorrisJobke** [comment]
@schiessle done :)

**Comment by MorrisJobke** [comment]
> @MorrisJobke can you have a look at the merge conflicts? Thanks!

Was only a !== that was already fixed by @nickvergessen in master :)

**Comment by MorrisJobke** [comment]
https://github.com/nextcloud/serverinfo/commit/92c09dd17e8eb59ea19ffe43b8e97809b1c7b0ae

**Comment by schiessle** [comment]
Thanks Morris! :)

**Comment by MorrisJobke** [comment]
@schiessle @karlitschek I would like to backport this to stable10

**Comment by nickvergessen** [comment]
You can't have the same wish twice, my son!
https://github.com/nextcloud/serverinfo/pull/35

**Comment by MorrisJobke** [comment]
> You can't have the same wish twice, my son!

🙈

**Pull request merged**
