### PR TITLE
Initial try to support illumos/Solaris to fix #263.

### LINKED ISSUE #263: Server Information is very incomplete on OmniOS
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Install nextCloud on a illumos-based server, e.g. with [pkgsrc](https://pkgsrc.joyent.com): `pfexec pkgin in php74-nextcloud`.
2. Set up your installation as usual.
3. Visit the Administration -> System page.

### Expected behaviour
You should see Uptime, CPU and Memory information about your system.

### Actual behaviour
You don’t.

Bildschirmfoto 2020-12-14 um 09 59 57

### Server configuration

**Operating system:** OmniOS CE r151036

**Web server:** nginx

**Database:** MariaDB

**PHP version:** 7.4

**Nextcloud version:** (see Nextcloud admin page) 20.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Continuously updated since nextCloud 13.

**Where did you install Nextcloud from:** pkgsrc, as described.

**Signing status:**
<details>
<summary>Signing status</summary>

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- files_rightclick
	- EXTRA_FILE
		- README.md

Raw output
==========
Array
(
    [files_rightclick] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [README.md] => Array
                        (
                            [expected] => 
                            [current] => 008148d723136644c2542312557ed5b9db1af5de6797a221d221012ae0ad367b2daca4774bcaba8936ec8394093b83c3e3f2d8e7c52e5f5882e28579dffe99e2
                        )

                )

        )

)
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.3
  - calendar: 2.1.2
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 3.4.2
  - contactsinteraction: 1.1.0
  - dav: 1.16.1
  - federatedfilesharing: 1.10.1
  - federation: 1.10.1
  - files: 1.15.0
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.0
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - photos: 1.2.0
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - updatenotification: 1.10.0
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
Disabled:
  - admin_audit
  - dashboard
  - encryption
  - files_external
  - recommendations
  - sharebymail
  - user_ldap
  - user_status
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.rosaelefanten.org"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "20.0.2.2",
        "overwrite.cli.url": "https:\/\/cloud.rosaelefanten.org",
        "installed": true,
        "theme": "",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "log_rotate_size": 10485760,
        "loglevel": 2,
        "maintenance": false,
        "app_install_overwrite": [
            "calendar"
        ],
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "post": 0
        }
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no (but planned)

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Safari 14

**Operating system:** macOS 11

#### Web server error log
<details>
<summary>Web server error log</summary>

```
2020/12/12 14:16:26 [error] 534#0: accept4() failed (130: Software caused connection abort)
2020/12/13 21:09:17 [error] 532#0: *3298 open() "/opt/local/share/nextcloud/c/version.js" failed (2: No such file or directory), client: 178.128.36.39, server: cloud.rosaelefanten.org, request: "GET /c/version.js HTTP/1.1", host: "185.207.106.218"
2020/12/13 21:09:18 [error] 532#0: *3306 open() "/opt/local/share/nextcloud/stalker_portal/c/version.js" failed (2: No such file or directory), client: 178.128.36.39, server: cloud.rosaelefanten.org, request: "GET /stalker_portal/c/version.js HTTP/1.1", host: "185.207.106.218"
2020/12/13 21:40:55 [error] 532#0: *3514 access forbidden by rule, client: 77.1.63.68, server: cloud.rosaelefanten.org, request: "GET /data/.ocdata?t=1607892055229 HTTP/2.0", host: "cloud.rosaelefanten.org"
2020/12/14 05:38:48 [alert] 530#0: phantom event 0001 for closed and removed socket 13
2020/12/14 05:39:05 [alert] 529#0: phantom event 0001 for closed and removed socket 13
2020/12/14 05:39:22 [alert] 531#0: phantom event 0001 for closed and removed socket 13
2020/12/14 05:39:23 [alert] 531#0: phantom event 0001 for closed and removed socket 13
2020/12/14 05:39:50 [alert] 531#0: phantom event 0001 for closed and removed socket 13
2020/12/14 05:39:53 [alert] 531#0: phantom event 0001 for closed and removed socket 13
2020/12/14 05:39:58 [alert] 530#0: phantom event 0001 for closed and removed socket 13
2020/12/14 05:40:04 [alert] 530#0: phantom event 0001 for closed and removed socket 13
2020/12/14 05:40:09 [alert] 531#0: phantom event 0001 for closed and removed socket 13
2020/12/14 05:40:15 [alert] 532#0: phantom event 0001 for closed and removed socket 12
2020/12/14 05:40:20 [alert] 530#0: phantom event 0001 for closed and removed socket 13
2020/12/14 05:40:21 [alert] 530#0: phantom event 0001 for closed and removed socket 13
2020/12/14 05:40:23 [alert] 529#0: phantom event 0001 for closed and removed socket 13
2020/12/14 05:40:25 [alert] 529#0: phantom event 0001 for closed and removed socket 13
2020/12/14 05:40:26 [alert] 530#0: phantom event 0001 for closed and removed socket 13
2020/12/14 05:40:28 [alert] 530#0: phantom event 0001 for closed and removed socket 13
2020/12/14 05:40:28 [alert] 530#0: phantom event 0001 for closed and removed socket 13
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
(Empty yet.)
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
[Error] Refused to execute a script because its hash, its nonce, or 'unsafe-inline' does not appear in the script-src directive of the Content Security Policy. (serverinfo, line 0)
[Warning] No OC found (main.js, line 1)
[Log] JQMIGRATE: Migrate is installed, version 1.4.1 (main.js, line 1)
[Warning] jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. (main.js, line 1)
[Warning] $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. (main.js, line 1)
[Warning] $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. (main.js, line 1)
[Warning] $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. (main.js, line 1)
[Warning] $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. (main.js, line 1)
[Debug] Notifications permissions granted (notifications-main.js, line 303)
[Warning] jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. (main.js, line 1)
[Warning] moment is deprecated: please ship your own, this will be removed in Nextcloud 20 (main.js, line 1)
[Warning] jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. (main.js, line 1)
[Warning] jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. (main.js, line 1)
[Warning] jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. (main.js, line 1)
[Info] session heartbeat polling started (main.js, line 1)
[Warning] $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. (main.js, line 1)
[Warning] $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. (main.js, line 1)
[Debug] Files_PDFViewer initialized for public page – Object (files_pdfviewer-public.js, line 44)
Object
[Warning] $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. (main.js, line 1)
[Warning] $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. (main.js, line 1)
[Warning] $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. (main.js, line 1)
[Warning] $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. (main.js, line 1)
[Warning] $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. (main.js, line 1)
[Warning] $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. (main.js, line 1)
[Warning] $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. (main.js, line 1)
[Warning] $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. (main.js, line 1)
[Warning] $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. (main.js, line 1)
[Warning] $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. (main.js, line 1)
[Warning] $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. (main.js, line 1)
[Warning] $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. (main.js, line 1)
[Warning] $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. (main.js, line 1)
[Warning] $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. (main.js, line 1)
[Warning] $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. (main.js, line 1)
[Warning] $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. (main.js, line 1)
[Warning] $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. (main.js, line 1)
[Warning] $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. (main.js, line 1)
[Warning] $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. (main.js, line 1)
[Warning] $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. (main.js, line 1)
[Warning] $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. (main.js, line 1)
[Warning] $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. (main.js, line 1)
[Warning] $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. (main.js, line 1)
[Warning] $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. (main.js, line 1)
[Warning] $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. (main.js, line 1)
[Warning] $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. (main.js, line 1)
[Warning] $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. (main.js, line 1)
[Error] Unrecognized Content-Security-Policy directive 'worker-src'. (x2)

[Error] Refused to execute a script because its hash, its nonce, or 'unsafe-inline' does not appear in the script-src directive of the Content Security Policy. (about:blank, line 0)
[Error] Unrecognized Content-Security-Policy directive 'worker-src'. (x2)

[Error] Refused to execute a script because its hash, its nonce, or 'unsafe-inline' does not appear in the script-src directive of the Content Security Policy. (about:blank, line 0)
[Warning] Clipboard is deprecated: please ship your own, this will be removed in Nextcloud 20 (main.js, line 1)
[Debug] [DEBUG] unified-search: Unified Search initialized with the following providers – Object (unified-search.js, line 1)
Object
```
</details>

### PR DESCRIPTION
**Pull request by dertuxmalwieder**

### CODE REVIEW

**Comment by kesselb** [comment]
Hi, can you rebase your branch to pull the latest changes?

**Comment by dertuxmalwieder** [comment]
I have ceased any hope that this will ever be considered, to be honest.

**Comment by kesselb** [comment]
Sorry, it took so long to respond to your pull request :disappointed: 

I think we need to merge https://github.com/nextcloud/serverinfo/pull/411 first and update your implementation afterward. 

Could you run `php -r "var_export(net_get_interfaces());"` to export the network interfaces on your server?
I would like to know if the function also works on your sunos.
Don't forget to replace your public ip address with a private one if necessary.

**Comment by dertuxmalwieder** [comment]
Sure - here's the output:

```
array (
  'lo0' =>
  array (
    'unicast' =>
    array (
      0 =>
      array (
        'flags' => 137455732809,
        'family' => 2,
        'address' => '127.0.0.1',
        'netmask' => '255.0.0.0',
      ),
      1 =>
      array (
        'flags' => 137472510025,
        'family' => 26,
        'address' => '::1',
        'netmask' => 'ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff',
      ),
    ),
    'up' => true,
  ),
  'vioif0' =>
  array (
    'unicast' =>
    array (
      0 =>
      array (
        'flags' => 16795715,
        'family' => 2,
        'address' => '[redacted]',
        'netmask' => '255.255.252.0',
        'broadcast' => '[redacted]',
      ),
    ),
    'up' => true,
  ),
)
```

**Comment by kesselb** [comment]
https://github.com/nextcloud/serverinfo/pull/411 is merged. 

Could you update your pull request to use the new NetInterface logic?

**Comment by dertuxmalwieder** [comment]
> Could you update your pull request to use the new NetInterface logic?

I honestly don't know - you completely changes *almost everything* and now I'll need to understand WTH you did. Maybe it would have been *nice* to communicate with me during the production of the several changes.

**Pull request closed without merging**
