### PR TITLE
Properly fetch oracle database information

### PR DESCRIPTION
**Pull request by juliushaertl**
I'm not sure if the previous one ever worked, however querying `SELECT version FROM v$instance` doesn't on my test setup.

The additional catch block makes sure that we at least show something in case the query fails somewhere and not end up with an exception being thrown.

image

### CODE REVIEW

**Review by kesselb — APPROVED** [review]
LGTM :+1:

**Review by ChristophWurst — APPROVED** [review]
I remember that we've had an instance with Oracle where this didn't work either and it was some kind of permission problem. Can't tell what's the better approach. :+1:?

**Comment by kesselb** [comment]
Please don't forget to fix the code style ;)

**Pull request merged**
