### PR TITLE
Fix mobile view

### PR DESCRIPTION
**Pull request by Dennis1993**
Fix for https://github.com/nextcloud/serverinfo/issues/385

Before:
image

After:
image

Signed-off-by: Dennis1993 [Dennis1993@users.noreply.github.com](mailto:Dennis1993@users.noreply.github.com)

### CODE REVIEW

**Comment by szaimen** [comment]
Thanks! Though I fear it is still not working correctly:

<details>
<summary>click here</summary>

image


</details>


<details>
<summary>Tested with</summary>

```
docker run -it \
-p 8444:443 \
-e TRUSTED_DOMAIN=10.6.0.1 \
-e SERVERINFO_BRANCH=Dennis1993-patch-3 \
-v /:/host/ \
--name nextcloud-easy-test \
ghcr.io/szaimen/nextcloud-easy-test:latest
```

</details>

**Comment by Dennis1993** [comment]
Thank you!
Why is it not working?! :(
On my second testserver it is working too. I don't understand it.

image

**Comment by szaimen** [comment]
> Why is it not working?! :(
> On my second testserver it is working too. I don't understand it.

did you test with multiple connected drives or only with one?

**Comment by Dennis1993** [comment]
Both. My testserver A has only one disk and the second testserver has two drives. All other boxes are misaligned without this patch. If I use this patch, all boxed are correct aligned in mobile view.

**Comment by szaimen** [comment]
I just tried again and recorded a video for you:

https://user-images.githubusercontent.com/42591237/189678256-b07e31cc-6e15-447d-9732-27df309e7de4.mp4

**Comment by kesselb** [comment]
Thank you for the pull request 👍

I am closing it due to the lack of activity. If you have the time to continue, please make a new one.

**Pull request closed without merging**
