### PR TITLE
Fix memory, Add Mbps/Gbps to Speed, Add Number of Cores and fix block-size on Storage/Swap Size (FreeBSD)

### PR DESCRIPTION
**Pull request by constrict**
#210 Additional changes to show correct values

### CODE REVIEW

**Comment by kesselb** [comment]
https://github.com/nextcloud/serverinfo/blob/481df199df1c93342c1f9f922a9b3badd9dd3fa3/lib/SystemStatistics.php#L115-L126

`hw.physmem` was also used with the old code. It's not correct?

**Comment by constrict** [comment]
> `hw.physmem` was also used with the old code. It's not correct?

I suppose it depends on how you want to display the memory in two situations. The hw.realmem reports the reported real values of the memory totaled (in my case 64.00 GB). The hw.physmem displays the actual available memory that can be used by the system. So these are two different use case. I don't think either can be considered wrong in each situation.

The code in the FreeBSD.php is used to set the memory value in the image below. It does not appear to change any other value.

image

The old code is what sets the memory in the live usage display. FreeBSD.php has no influence on these values. SystemStatistics.php controls this image.
https://github.com/nextcloud/serverinfo/blob/481df199df1c93342c1f9f922a9b3badd9dd3fa3/lib/SystemStatistics.php#L115-L126

image

**Comment by VVD** [comment]
Is any possibility to merge it to stable19 branch or even stable18?

**Comment by kesselb** [comment]
> Is any possibility to merge it to stable19 branch or even stable18?

N as this a new feature.

**Comment by VVD** [comment]
> N as this a new feature.

For me it's bug fix - system information was incorrect before this patch.

**Comment by kesselb** [comment]
> system information was incorrect before this patch.

To be precise: System information was incorrect before this patch for the unsupported operating system FreeBSD. If that is such a problem for you just disable the serverinfo app ;)

**Comment by VVD** [comment]
:-P

Make FreeBSD supported operating system. :+1:

**Pull request merged**
