### PR TITLE
Added SunOS (tested against OmniOS)

### PR DESCRIPTION
**Pull request by pstumpe**
requires "top" package to be installed for parsing memory/swap info (cmd "pkg install top")
Signed-off-by: pstumpe <github@stumpe.ws>

### CODE REVIEW

**Comment by joshtrichards** [comment]
Is your implementation at all related to the one linked to from #263 by @dertuxmalwieder (they haven't submitted a PR, but did reference the issue in their fork's commit so I saw it pop up over there).

https://github.com/dertuxmalwieder/serverinfo/commit/ba979bf1ecc0f2352f4c481aa7d8cff8e10ce282

**Comment by dertuxmalwieder** [comment]
I wish that my first approach would have been merged. ;-)

**Comment by pstumpe** [comment]
Actually I took a look at the PRs from @dertuxmalwieder and tried to fix a few problems / errors in the code together with some small changes (e.g. as to show ZFS filesystems instead of actual discs).

**Comment by kesselb** [comment]
Thanks for your pull request :+1: 

Please add tests for your implementation. You may use the tests I wrote for the other SunOS / OmniOS as a starting point: https://github.com/nextcloud/serverinfo/compare/feat/sun-os

**Comment by kesselb** [comment]
Thanks for your work on this pull request. 

I’m closing it as the current implementation isn’t in a mergable state.

That said, I’m not against the feature itself! If someone wants to pick this up, I’d be happy to provide guidance to help move it forward. One important requirement for this feature is automated test coverage. This will ensure that the app remains maintainable for me without needing to set up a dedicated test installation on SunOS.

The [restricted mode](https://github.com/nextcloud/serverinfo?tab=readme-ov-file#restricted-mode--nextcloud-28) we introduced with Nextcloud 28 might help address your use case by preventing the execution of Linux commands that aren’t available on SunOS.

Thanks again for your contributions, and let me know if you have any questions or would like to revisit this in the future!

**Pull request closed without merging**
