### PR TITLE
Extend ServerInfo support to FreeBSD

### PR DESCRIPTION
**Pull request by constrict**
FreeBSD does not use /proc/ and values are set to unknown/-1

### CODE REVIEW

**Comment by kesselb** [comment]
https://github.com/nextcloud/serverinfo/issues/203#issuecomment-616232757 how to do it properly.

**Comment by constrict** [comment]
Thanks. Will work on doing this correctly.

**Comment by constrict** [comment]
Memory, uptime, CPU, network gateway, network interfaces are now available.

**Comment by constrict** [comment]
I am finished with this now. I made the changes needed to pass

**Pull request closed without merging**
