### PR TITLE
web-ui2

### PR DESCRIPTION
**Pull request by Ivansss**
Updated web UI as discussed with @jancborchardt 
Added active users statistics chart.
web-ui1
web-ui2
web-ui3

### CODE REVIEW

**Comment by schiessle** [comment]
@Ivansss what's the state of this pull request? Are you still working on it? Or can we merge it so that I can transfer it to a admin settings page?

**Comment by Ivansss** [comment]
@schiessle you can merge it.

**Comment by jancborchardt** [comment]
@schiessle @Ivansss if it’s included in the release, it should be on the admin settings page. Will this happen in time? :)

**Comment by schiessle** [comment]
> if it’s included in the release, it should be on the admin settings page. Will this happen in time? :)

If the new admin settings are ready for stable10 it will be in the release as a admin setting. If not it will be a stand-alone app... PR is already here and just waits: https://github.com/nextcloud/serverinfo/pull/18 :wink:

**Comment by jancborchardt** [comment]
@schiessle either way it should be in the admin settings. It’s an admin functionality and should definitely not be in the apps menu. Especially since we know that we will move it around it will otherwise lead to confusion on update.

**Comment by schiessle** [comment]
ihmo it's way to large to put it in the old admin settings, it is multiple pages on a normal screen

**Comment by schiessle** [comment]
if we want it in the admin settings, we need to think about a stripped-down version. Having all the graphs in the middle of the admin settings doesn't work

**Pull request merged**
