### PR TITLE
Rename the app to monitoring

### LINKED ISSUE #10: Rename it to "Monitoring"
I think _Monitoring_ describes better, what this app does.

cc @schiessle

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #10 

@MariusBluem @schiessle

### CODE REVIEW

**Comment by nickvergessen** [comment]
Adjusted

**Comment by MariusBluem** [comment]
...the Name of the repository?! 🙈

**Comment by nickvergessen** [comment]
Must match the appid and we cant change that atm

**Comment by MariusBluem** [comment]
How/when can we change the appid 🤔😬 @nickvergessen

**Comment by nickvergessen** [comment]
Create a new app, that does the same thing... The problem is updating people from existing apps. Since it's shipped we could do that, but not really worth it.

**Pull request merged**
