### PR TITLE
Replace "Active users" and "Shares" charts and replace custom tooltips on Disk chart.

### PR DESCRIPTION
**Pull request by JuliaKirschenheuter**
* Replace custom tooltips with additional information on Disk chart
* Replace Active users chart with plain information
* Replace Shares chart with plain (list) information
* Replace custom tooltip on copy button with native one and add success / error notification.

Fixes https://github.com/nextcloud/serverinfo/issues/418

|  Before   | After                                                        |
|-------------|---------------------------------------------------------------|
| Screenshot from 2023-01-24 16-48-06 | Screenshot from 2023-01-24 16-26-52 | 
| Screenshot from 2023-01-24 16-52-47 | Screenshot from 2023-01-24 16-54-28 |-------------|---------------------------------------------------------------|
| Screenshot from 2023-01-24 16-53-19 | Screenshot from 2023-01-24 16-54-33 |
| Screenshot from 2023-01-24 16-53-24 | Screenshot from 2023-01-24 16-54-37 |

### CODE REVIEW

**Comment by nickvergessen** [comment]
Finally no more weird graphs :D

When there are no shares we should however show "something"?
grafik

**Comment by JuliaKirschenheuter** [comment]
> Finally no more weird graphs :D
> 
> When there are no shares we should however show "something"? grafik

@kesselb https://github.com/nextcloud/serverinfo/pull/420/files#diff-b86b31801e087ecdaaf18d4d9db5f4362120f71c7173386d118e94b2f1899ac9R275 am i right?

**Comment by nickvergessen** [comment]
Should work, yeah
https://github.com/nextcloud/serverinfo/blob/master/lib/ShareStatistics.php#L50

**Comment by kesselb** [comment]
Welcome to the serverinfo team :partying_face:

**Review by kesselb — APPROVED** [review]

**Review by nickvergessen — APPROVED** [review]

**Pull request merged**
