### PR TITLE
Fix Memory

### PR DESCRIPTION
**Pull request by constrict**
Cast swapFree to integer to fix typeerror.

Fix total memory to use hw.realmem

### CODE REVIEW

**Comment by kesselb** [comment]
I don't see how to run into a type error? swapTotal is casted the line before and the free space is also casted.

Mind to add an example?

**Comment by kesselb** [comment]
https://github.com/nextcloud/serverinfo/blob/741936af1e628ffd1127ecefb3b7409522cfe334/tests/lib/FreeBSDTest.php#L57
https://github.com/nextcloud/serverinfo/blob/741936af1e628ffd1127ecefb3b7409522cfe334/tests/lib/FreeBSDTest.php#L75

Change `hw.physmem` to `hw.realmem` for a happy CI.

**Comment by constrict** [comment]
From my logs

```
{"Exception":"Exception","Message":"Argument 1 passed to OCA\\ServerInfo\\Resources\\Memory::setSwapFree() must be of the type int, float given, called in /usr/local/www/nextcloud/apps/serverinfo/lib/OperatingSystems/FreeBSD.php on line 57"
```

**Comment by kesselb** [comment]
Mind to share the output of `/usr/sbin/swapinfo -k`?

**Comment by constrict** [comment]
> 
> 
> Mind to share the output of `/usr/sbin/swapinfo -k`?

```
Device          1K-blocks     Used    Avail Capacity
/dev/ada0p3       3744300   269052  3475248     7%
```

**Comment by kesselb** [comment]
`(int)($matches['Used'][0]) / 1024`

Ah. The closing bracket is wrong in the above code. It should be `(int)($matches['Used'][0] / 1024)`. First divide by 1024 and cast afterwards: `$data->setSwapFree((int)($data->getSwapTotal() - ($matches['Used'][0] / 1024)));`

Mind to update your patch and adjust the tests for `hw.realmem`?

**Comment by kesselb** [comment]
> https://github.com/nextcloud/serverinfo/blob/741936af1e628ffd1127ecefb3b7409522cfe334/tests/lib/FreeBSDTest.php#L75
> 
> Change `hw.physmem` to `hw.realmem` for a happy CI.

Please update this test case as well.

**Review by kesselb — APPROVED** [review]
Thanks 👍

**Pull request merged**
