### PR TITLE
fix: allow dot in mounted on

### LINKED ISSUE #664: Buggy regular expression for available disks
Hello,

this is the output of "df -TPk" for my machine:

Filesystem     Type     1024-blocks      Used Available Capacity Mounted on
/dev/vda4      ext4        51290592   3560060  45092708       8% /
devtmpfs       devtmpfs        4096         8      4088       1% /dev
tmpfs          tmpfs        8189732         0   8189732       0% /dev/shm
tmpfs          tmpfs        3275896    152068   3123828       5% /run
tmpfs          tmpfs        1637944         4   1637940       1% /run/user/0
/dev/vda5      ext4       205314024 110088996  84722884      57% /nextcloud/my.cloud.domain.xx

Once the script passes through the line:

preg_match_all($pattern, $meminfo, $matches);

The $matches array contains every line except the last one, which is the most important to me. For some reason, the regular expression is cutting that last line...

I'm using NC 29.0.4 on OpenSUSE 15.6.

Thanks.

### PR DESCRIPTION
**Pull request by kesselb**
Fix #664

### CODE REVIEW

**Review by provokateurin — APPROVED** [review]
Folder names with dots what could go wrong

**Comment by kesselb** [comment]
:see_no_evil:

**Pull request merged**
