### PR TITLE
Modified info.xml <dependencies> tag

### PR DESCRIPTION
**Pull request by totalcaos**
Modified dependency min-version to version 8.0
Added dependency max-version at version 10.0

### CODE REVIEW

**Comment by nickvergessen** [comment]
I think we should use 9.2 for both on master, @schiessle

**Comment by schiessle** [comment]
We release it with stable10, so I would keep min version at 9.1 and increase max version to 9.2 for master. 

Min version 8.0 makes no sense, because there is no Nextcloud 8 and max 10 doesn't make sense because we can't tell today if it will be compatible with 10 (whatever 10 will be, at the moment we keep it align with ownCloud, so it would mean that it woks with whatever ownCloud10 and Nextcloud X will look like, something we just can tell as of today)

**Comment by totalcaos** [comment]
updated as per @schiessle's comments

**Comment by schiessle** [comment]
thanks @totalcaos :+1:

**Pull request merged**
