### PR TITLE
Add icon to admin page sidebar

### PR DESCRIPTION
**Pull request by MorrisJobke**
* follow up to nextcloud/server#3151
Before:

bildschirmfoto 2017-01-24 um 10 58 41

After:

bildschirmfoto 2017-01-24 um 11 15 36

### CODE REVIEW

**Comment by MorrisJobke** [comment]
> Beautiful icon! I like it a lot!

It's the copy of the normal icon with inverted colors :)

**Comment by skjnldsv** [comment]
Still! 😆

**Comment by jancborchardt** [comment]
By the way … maybe »Information« is a better German translation that »Überwachung«?

**Comment by MorrisJobke** [comment]
> By the way … maybe »Information« is a better German translation that »Überwachung«?

Fixed. But you could do this as well 😉

**Pull request merged**
