### PR TITLE
Create fixup.yml

### PR DESCRIPTION
**Pull request by kesselb**
Hey ;) We are still using the old fixupbot over here.

Could you please remove fixupbot and merge this pr?

### CODE REVIEW

**Comment by nickvergessen** [comment]
> Could you please remove fixupbot 

???

**Comment by nickvergessen** [comment]
Ah  you meant the required CI check... done

**Comment by kesselb** [comment]
> Ah you meant the required CI check... done

Thank you! Can you approve this pr and make the new fixup action a required ci check?

**Review by blizzz — APPROVED** [review]

**Comment by blizzz** [comment]
> > Ah you meant the required CI check... done
> 
> Thank you! Can you approve this pr, merge and make the new fixup action a required ci check?

done

**Pull request merged**
